In [60]:
import pandas as pd

In [61]:
bjj = pd.DataFrame({
'day': ['Mon', 'Wed', 'Fri', 'Sat'],
'minutes': [90, 60, 90, 120],
'rolls': [5, 3, 6, 8],
})
bjj

   day  minutes  rolls
0  Mon       90      5
1  Wed       60      3
2  Fri       90      6
3  Sat      120      8

## Question 1 - 3

In [62]:
bjj['minutes']

0     90
1     60
2     90
3    120
Name: minutes, dtype: int64

In [63]:
type(bjj['minutes'])
# pandas.Series

# ' - single quotes
# " - double quotes

pandas.Series

## Question 4 - 6

In [64]:
bjj.iloc[1]

day        Wed
minutes     60
rolls        3
Name: 1, dtype: object

In [65]:
bjj.loc[1]

day        Wed
minutes     60
rolls        3
Name: 1, dtype: object

In [66]:
sorted_bjj = bjj.sort_values('minutes')
sorted_bjj

   day  minutes  rolls
1  Wed       60      3
0  Mon       90      5
2  Fri       90      6
3  Sat      120      8

In [67]:
sorted_bjj.iloc[1] # position 1

day        Mon
minutes     90
rolls        5
Name: 0, dtype: object

In [68]:
bjj.loc[1] # label 1

day        Wed
minutes     60
rolls        3
Name: 1, dtype: object

In [69]:
# Now that we sorted values based upon minutes, monday is index 1, while Wednesday has column value 1 assigned to it.
# In simple words, iloc tells what is located, while loc tells where does something lies.

## Question 7 - 9

In [70]:
bjj[bjj['minutes'] > 80]

   day  minutes  rolls
0  Mon       90      5
2  Fri       90      6
3  Sat      120      8

In [71]:
bjj['hard'] = bjj['rolls'] > 5
bjj

   day  minutes  rolls   hard
0  Mon       90      5  False
1  Wed       60      3  False
2  Fri       90      6   True
3  Sat      120      8   True

In [72]:
bjj['minutes']
# Returns data type - Series

0     90
1     60
2     90
3    120
Name: minutes, dtype: int64

In [73]:
bjj[['minutes']]
# Returns data type - DataFrame

   minutes
0       90
1       60
2       90
3      120

## Question 10 - 12

In [74]:
tough_sessions = bjj[(bjj['minutes'] > 80) & (bjj['rolls'] >= 5)]
tough_sessions

   day  minutes  rolls   hard
0  Mon       90      5  False
2  Fri       90      6   True
3  Sat      120      8   True

In [75]:
len(tough_sessions)

3

In [76]:
# tough_sessions = bjj[(bjj['minutes'] > 80) and (bjj['rolls'] >= 5)]
# ---> ValueError /// The truth value of a Series is ambiguous.

#tough_sessions = bjj[bjj['minutes'] > 80 & bjj['rolls'] >= 5]
# ---> ValueError /// The truth value of a Series is ambiguous.

## Question 13 - 15

In [ ]:
# NONE