In [75]:
import pandas as pd
import numpy as np

In [76]:
# time: 20 min

## Questions 1 - 3

In [77]:
s = pd.Series([90, 60, 25, np.nan, 35, 15])

In [78]:
print(s.dropna().mean()) # honest, one row lighter

45.0

In [79]:
print(s.fillna(0).mean()) # zero is a real value, not a blank

37.5

In [80]:
print(s.fillna(s.mean()).mean()) # keeps the average, invents certainty

45.0

In such cases I would rather drop NaN values and inform coach of it

## Questions 4 - 6

In [81]:
bjj = pd.DataFrame({
'belt': ['blue', 'white', 'blue', 'purple','red','white','white'],
'minutes': [90, 60, 90, 120, 180, 60,45],
'rolls': [5, 3, 6, 8, 12, 3, 5],
})
bjj

     belt  minutes  rolls
0    blue       90      5
1   white       60      3
2    blue       90      6
3  purple      120      8
4     red      180     12
5   white       60      3
6   white       45      5

In [82]:
bjj.groupby('belt')['minutes'].mean()

belt
blue       90.0
purple    120.0
red       180.0
white      55.0
Name: minutes, dtype: float64

In [83]:
type(bjj.groupby('belt')['minutes'].mean())
# It is Series instead of DataFrame because I select one column instead of multiple
# If I to use [[]] instead of [], then I would get a tables

pandas.Series

In [84]:
bjj.groupby('belt')[['minutes']].mean()

        minutes
belt
blue       90.0
purple    120.0
red       180.0
white      55.0

In [85]:
type(bjj.groupby('belt')[['minutes']].mean())

pandas.DataFrame

In [86]:
bjj.groupby('belt')

## Questions 7 - 9

In [87]:
print(bjj.groupby('belt')['minutes'].agg(['mean', 'count']))

         mean  count
belt
blue     90.0      2
purple  120.0      1
red     180.0      1
white    55.0      3

Smallest group is purple/red belt with only 1 session, so its average is least trustworthy number in this table

In [88]:
result = bjj.groupby('belt')['minutes'].agg(['mean', 'count']).reset_index()
result

     belt   mean  count
0    blue   90.0      2
1  purple  120.0      1
2     red  180.0      1
3   white   55.0      3

.reset_index() allows to bring back belts used for .groupby() back as separate column instead of indexes

In [91]:
print(result.sort_values('mean', ascending=False))

     belt   mean  count
2     red  180.0      1
1  purple  120.0      1
0    blue   90.0      2
3   white   55.0      3

In [90]:
print(result) # unchanged — sorting gaves a copy

     belt   mean  count
0    blue   90.0      2
1  purple  120.0      1
2     red  180.0      1
3   white   55.0      3