In [145]:
# time : ~30 min

In [146]:
import pandas as pd
import numpy as np
import numpy.random as rnd

## Questions 1-3

In [147]:
s = pd.Series([1, 2, 99])

In [148]:
print(s.mean())

34.0

In [149]:
print(s.median())

2.0

In [150]:
df = pd.DataFrame(rnd.randint(0, 99, size=(3,4)))
df

    0   1   2   3
0  25  21  83  22
1  97  68  79  29
2  91  85  59  42

In [151]:
# rows first, columns second
df.shape

(3, 4)

## Questions 4 - 6

In [152]:
bjj = pd.DataFrame({
'day': ['Mon', 'Wed', 'Fri', 'Sat'],
'minutes': [90, 60, 90, 120],
'rolls': [5, 3, 6, 8],
})
bjj

   day  minutes  rolls
0  Mon       90      5
1  Wed       60      3
2  Fri       90      6
3  Sat      120      8

In [153]:
bjj.loc[1, 'minutes'] = np.nan # say this out loud: "lock", not "log"
bjj.loc[3] = np.nan
bjj

   day  minutes  rolls
0  Mon     90.0    5.0
1  Wed      NaN    3.0
2  Fri     90.0    6.0
3  NaN      NaN    NaN

In [154]:
print(bjj.isnull().sum())

day        1
minutes    2
rolls      1
dtype: int64

In [155]:
bjj.info()
# day and rolls columns have 1 NaN values
# column minutes have 2 NaN values

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   day      3 non-null      str
 1   minutes  2 non-null      float64
 2   rolls    3 non-null      float64
dtypes: float64(2), str(1)
memory usage: 228.0 bytes

## Questions 7 - 9

In [156]:
bjj

   day  minutes  rolls
0  Mon     90.0    5.0
1  Wed      NaN    3.0
2  Fri     90.0    6.0
3  NaN      NaN    NaN

In [157]:
print(len(bjj)) # before

4

In [158]:
print(len(bjj.dropna())) # after dropping

2

In [159]:
print(bjj.fillna(25)) # after filling

   day  minutes  rolls
0  Mon     90.0    5.0
1  Wed     25.0    3.0
2  Fri     90.0    6.0
3   25     25.0   25.0

In [160]:
bjj.dropna(inplace=True)

I have decided to remove all NaN values in order to keep all aggregations operations in order

## Questions 10 - 12

In [162]:
bjj['hours'] = bjj['minutes'].apply(lambda x: x / 60)
print(bjj)

   day  minutes  rolls  hours
0  Mon     90.0    5.0    1.5
2  Fri     90.0    6.0    1.5

Take the value x and divide it by 60