In [20]:
# time: ~20 min

In [21]:
import numpy as np
import pandas as pd

## Questions 1 - 3

In [22]:
bjj = pd.DataFrame({
'member_id': [1, 2, 3,4,5,6,7,8,9],
'belt': ['blue', 'white', 'blue', 'purple','red','white','purple','black','blue'],
'minutes': [90, 60, 90, 120, 180, 60,45,200,300],
'rolls': [5, 3, 6, 8, 12, 3, 5,4,20],
})
bjj

   member_id    belt  minutes  rolls
0          1    blue       90      5
1          2   white       60      3
2          3    blue       90      6
3          4  purple      120      8
4          5     red      180     12
5          6   white       60      3
6          7  purple       45      5
7          8   black      200      4
8          9    blue      300     20

Groups bjj dataframe by belt, then takes minutes column, applies aggregation mean and count and resets indexes so they would still have belts as a column instead of an index

In [23]:
result = bjj.groupby('belt')['minutes'].agg(['mean', 'count']).reset_index()
result

     belt   mean  count
0   black  200.0      1
1    blue  160.0      3
2  purple   82.5      2
3     red  180.0      1
4   white   60.0      2

In [24]:
result.sort_values('mean', ascending=False)

     belt   mean  count
0   black  200.0      1
3     red  180.0      1
1    blue  160.0      3
2  purple   82.5      2
4   white   60.0      2

In [25]:
result

     belt   mean  count
0   black  200.0      1
1    blue  160.0      3
2  purple   82.5      2
3     red  180.0      1
4   white   60.0      2

Unchanged — sorting handed a copy of result.
It is occurring because sort_values() hands back a copy of a variable instead of interacting with a variable itself

## Questions 4 - 6

In [26]:
first = bjj.head(5)
first

   member_id    belt  minutes  rolls
0          1    blue       90      5
1          2   white       60      3
2          3    blue       90      6
3          4  purple      120      8
4          5     red      180     12

In [27]:
second = bjj.tail(5)
second

   member_id    belt  minutes  rolls
4          5     red      180     12
5          6   white       60      3
6          7  purple       45      5
7          8   black      200      4
8          9    blue      300     20

In [28]:
pd.concat([first, second])

   member_id    belt  minutes  rolls
0          1    blue       90      5
1          2   white       60      3
2          3    blue       90      6
3          4  purple      120      8
4          5     red      180     12
4          5     red      180     12
5          6   white       60      3
6          7  purple       45      5
7          8   black      200      4
8          9    blue      300     20

In [29]:
pd.concat([first, second], ignore_index=True)

   member_id    belt  minutes  rolls
0          1    blue       90      5
1          2   white       60      3
2          3    blue       90      6
3          4  purple      120      8
4          5     red      180     12
5          5     red      180     12
6          6   white       60      3
7          7  purple       45      5
8          8   black      200      4
9          9    blue      300     20

## Questions 7 - 9

In [30]:
belts = pd.DataFrame({
'member_id': [1, 2, 3],
'belt': ['white', 'blue', 'purple']})
belts

   member_id    belt
0          1   white
1          2    blue
2          3  purple

In [31]:
# I expect 3 rows back, because there is only 3 users in both that have same member_id

In [32]:
merged = pd.merge(bjj, belts, on='member_id')
merged

   member_id belt_x  minutes  rolls  belt_y
0          1   blue       90      5   white
1          2  white       60      3    blue
2          3   blue       90      6  purple

In [33]:
merged.shape[0]

3

## Questions 10 - 12

In [34]:
inner = pd.merge(bjj, belts, on='member_id') # default
inner

   member_id belt_x  minutes  rolls  belt_y
0          1   blue       90      5   white
1          2  white       60      3    blue
2          3   blue       90      6  purple

In [35]:
left = pd.merge(bjj, belts, on='member_id', how='left')
left

   member_id  belt_x  minutes  rolls  belt_y
0          1    blue       90      5   white
1          2   white       60      3    blue
2          3    blue       90      6  purple
3          4  purple      120      8     NaN
4          5     red      180     12     NaN
5          6   white       60      3     NaN
6          7  purple       45      5     NaN
7          8   black      200      4     NaN
8          9    blue      300     20     NaN

In [36]:
print(inner.shape[0], left.shape[0])

3 9

In [37]:
print(left[left[['belt_x']].isna()]) # the rows the inner join threw away

## Inner dropped 6 rows

   member_id belt_x  minutes  rolls belt_y
0        NaN    NaN      NaN    NaN    NaN
1        NaN    NaN      NaN    NaN    NaN
2        NaN    NaN      NaN    NaN    NaN
3        NaN    NaN      NaN    NaN    NaN
4        NaN    NaN      NaN    NaN    NaN
5        NaN    NaN      NaN    NaN    NaN
6        NaN    NaN      NaN    NaN    NaN
7        NaN    NaN      NaN    NaN    NaN
8        NaN    NaN      NaN    NaN    NaN