In [138]:
import numpy as np
import pandas as pd

In [139]:
bjj = pd.DataFrame({
'day': ['Mon', 'Wed', 'Fri', 'Sat'],
'minutes': [90, 60, 90, 120],
'rolls': [5, 3, 6, 8],
})
bjj

   day  minutes  rolls
0  Mon       90      5
1  Wed       60      3
2  Fri       90      6
3  Sat      120      8

## Questions 1 - 3

In [140]:
bjj['minutes']
# bjj - open square bracket - single quote - minutes - single quite - close square bracket

0     90
1     60
2     90
3    120
Name: minutes, dtype: int64

In [141]:
type(bjj['minutes'])

pandas.Series

In [142]:
bjj[['minutes']]
# bjj - open square bracket - open square bracket - single quote - minutes - single quote - close square bracket - close square bracket

   minutes
0       90
1       60
2       90
3      120

In [143]:
type(bjj[['minutes']])

pandas.DataFrame

## Questions 4 - 6

In [144]:
arr = np.arange(12).reshape(3, 4)

In [145]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
arr.shape

(3, 4)

In [147]:
arr.ndim

2

In [148]:
bjj.values
# .values takes a DataFrame and gives just the raw data inside it as a NumPy array.

array([['Mon', 90, 5],
       ['Wed', 60, 3],
       ['Fri', 90, 6],
       ['Sat', 120, 8]], dtype=object)

In [149]:
type(bjj.values)

numpy.ndarray

## Questions 7 - 9

In [150]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
arr.sum(axis=0)
# get column summaries

array([12, 15, 18, 21])

In [152]:
len(arr.sum(axis=0))

4

In [153]:
arr.sum(axis=1)
# get row summaries

array([ 6, 22, 38])

In [154]:
len(arr.sum(axis=1))

3

## Questions 10 - 12

In [155]:
np.random.seed(42)
rolls = np.random.randint(1, 10, size=(3, 4))

In [156]:
rolls

array([[7, 4, 8, 5],
       [7, 3, 7, 8],
       [5, 4, 8, 8]])

In [157]:
rolls.mean(axis=0)

array([6.33333333, 3.66666667, 7.66666667, 7.        ])

In [158]:
rolls.mean(axis=1)

array([6.  , 6.25, 6.25])

In [159]:
# rolls.mean(axis=2)
# AxisError
# Axis 2 is out of bounds for array of dimension 2

## Questions 13 - 15

In [ ]:
# None